### ISSUE TITLE
ModuleNotFoundErrowhen using ai_engine imports

### ISSUE THREAD

**Issue by hchou3** [fetchai/uAgents#693]
### Prerequisites

- [x] I checked the [documentation](https://fetch.ai/docs) and found no answer to my problem
- [x] I checked the [existing issues](https://github.com/fetchai/uAgents/issues) and made sure there are no similar bug reports

### Category

Bug (unexpected behavior)

### Observed Behavior

Is anyone running into an error when attempting to use uagents-ai-engine. I've testing it with multiple imports from the package and none have worked:
Imports:
from ai_engine.chitchat import ChitChatDialogue
from ai_engine.messages import DialogueMessage
from ai_engine.dialogue import EdgeMetadata, EdgeDescription
Error:
    from uagents.models import Model
ModuleNotFoundError: No module named 'uagents.models'
 My versions for uagents and uagents-ai-engineare 0.22.3 and  0.10.0 respectively.

### Version

0.22.3

### Environment Details (Optional)

```markdown

```

### Failure Logs (Optional)

```shell

```

### Additional Information (Optional)

```markdown

```

**Comment by jrriehl** [comment]
Thanks for the bug report. It should be fixed now. Let us know if you have any more issues.

**Comment by hchou3** [comment]
Hey, I just tried using uagents-ai-engnine again today. I'm using virtual python env on VSCode so I reset everything (uninstalled and reinstalled) but I'm still getting the same error:

  File "", line 5, in <module>
    from ai_engine.chitchat import ChitChatDialogue
  File "", line 1, in <module>
    from ai_engine.types import KeyValue, UAgentResponseType, UAgentResponse, BookingRequest
  File "", line 1, in <module>
    from uagents.models import Model
ModuleNotFoundError: No module named 'uagents.models'

I only uninstalled and reinstalled uagents and uagents-ai-engine.
